### PR TITLE
Fix tp snipe simple

### PR DESCRIPTION
**Pull request by oversword**
Depends on https://github.com/minetest-mods/teleport-request/pull/45
Depends on https://github.com/minetest-mods/teleport-request/pull/46
Depends on https://github.com/minetest-mods/teleport-request/pull/47

(Attempts) to fix the TP sniping issue / the issue with unexpected behaviour
Fixes https://github.com/BlockySurvival/issue-tracker/issues/83
Fixes https://github.com/BlockySurvival/issue-tracker/issues/320

The fix here attempts to allow only one request per user at any time, to avoid any conflicts with multiple requests

These changes definitely need some consideration and testing, I'm unsure if they actually "fix" the problem, I have just attempted to prevent it from happening in the first place.

This the is "simple" solution, I conceived of a more complex solution based on the discussions in https://github.com/BlockySurvival/issue-tracker/issues/83 , but decided to implement this one first as it was faster to write.

- These changes may make the mod unpleasant to use, it may feel like it's constantly telling you it's not working
- This only works if the lists are correctly cleared, something which is not guaranteed, but I may have only seen this happening in the the previous broken states
- We might also want to send a message to the receiver telling them someone attempted to make another request so they can talk to them after they have cleared their current request

### CODE REVIEW

**Comment by Panquesito7** [comment]
Could you try to make a simple PR with one branch to test the changes easier and incorporate them easier (**if that's fine for you**)? Thanks.

**Comment by oversword** [comment]
> Could you try to make a simple PR with one branch

I would really rather merge the other ones in first, I don't mind waiting for this one, the others were done to make programming this one easier

**Review by Panquesito7 — APPROVED** [review]

**Comment by Panquesito7** [comment]
Thank you for your contributions! 😄🚀

**Comment by oversword** [comment]
@Panquesito7 Woah woah woah why did you merge this one? Are you sure this is the best fix?
I think the complex solution at least deserves considering https://github.com/minetest-mods/teleport-request/pull/49

**Comment by Panquesito7** [comment]
Should I revert this one, then? I'm kinda confused...
We can discuss this via Discord. My username is Panquesito7#3723.

**Comment by Panquesito7** [comment]
I reviewed this PR, and it looks fine.

**Pull request merged**
