### PR TITLE
Fix after

### PR DESCRIPTION
**Pull request by oversword**
Depends on https://github.com/minetest-mods/teleport-request/pull/45

This doesn't *fix* anything, but I kind of think it's bad practice to send some vars in to the `minetest.after` and rely on others being in the scope outside it. This makes it more consistent.

My following MRs (I'm just building up to fixing the actual bugs) will branch off of this one so it will probably go in anyhow x)

Will need to test that the correct messages are sent to the correct person, I will check this by eye thoroughly though

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks.

**Comment by Panquesito7** [comment]
Hmm, I merged in the wrong order. 😅

**Comment by Panquesito7** [comment]
Hmm, what did I do wrong here? Sorry for messing up. Could you please re-make this PR? Thanks.

**Comment by oversword** [comment]
> Hmm, I merged in the wrong order.

I'll resolve in a sec, just finishing up the complex solution to TP snipes

**Comment by oversword** [comment]
@Panquesito7 if #47 was merged then I don't think this one needs to be, master now contains the changes from both

**Pull request closed without merging**
